---
title: "Assignment 1"
---

# Assignment 1

```{r}
1 + 1
```

My first assignment has two parts.

## (a)

I will give brief information about the video, which you can access [here](https://www.youtube.com/watch?v=ttLnLdU1-CQ).

  The video begins with the expectations of Tracy Teal, an American bioinformatician and general manager of Data Carpentry, from her educational life. She says that one of the factors in choosing the department was to be able to deal with science without having to communicate with anyone, but then she realizes that just doing science is not enough and it is necessary to share the results she finds. In the words of Lewis Kirvan, 'Sometimes you just need words'. Se realizes that she can use writing to present her findings and that she enjoys it very much. However, preparing presentations is still an area that she is not excited about until she meets Quarto. After stating that Quarto makes this job fun, Tracy Teal gives an example. In addition to the ability to change the created page with code plug-ins from the software part called 'source'; changes made in the 'visual' part, that is, the part where the visual reflection of the coding is displayed, are also added to the 'source' part. She adds that it was very beneficial for her to be able to see the changes on the page synchronously after rendering the code she wrote. 
  Another thing Tracy Teal liked about Quarto was the ease of visual editing. She mentions that editing visual additions is easy and usable, and that editing can be complicated depending on your time.
  Another feature that makes things easier while preparing slides is the ability to add speaker notes. With Quarto, the person preparing the presentation can view the current page, the next page, the time, the time since the beginning and the notes she wrote for himself on the same page. Therefore, it helped her to explain what she wanted to say during the presentation more clearly. 
  Stating that she has been giving trainings about data and its utilization for a long time, Tracy Teal talked about the visual effect of data in the field of scienctific communication; She mentions that with Quarto, both software, slides and figures are integrated in the same file, which provides ease of use. She added that when she looks at the code in the future, she does not waste time to reveal what she has done in the past, because all components can be accessed in the same code.
  Another ease of use for her was the enjoyable themes.
## (b)
